name: NPM Package CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.0

      - name: Install NPM dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
     - name: Publish the package on NPM
       uses: JS-DevTools/npm-publish@v1
       with:
          access: "public"
          token: ${{ secrets.NPM_AUTH_TOKEN }}
